Link sandesh tests against boost_thread library
sandesh tests have multiple build failures due to linking errors, e.g.:
```
undefined reference to `vtable for boost::detail::thread_data_base'
```

Add boost_thread to the library list.

Partial-Bug: #1746451
Change-Id: Ie0217f481c21ad5cf5e5564bf08f1034c98dbf1a