Add bottle to the pysandesh requirements list
We're seeing UT failures ending with:

ImportError: No module named bottle

Add bottle to the list of pysandesh dependencies so it gets installed.

Partial-Bug: #1746451
Change-Id: Icc228344923219d0dff5e798ffe54c7cb672e445